/**
 * Tray Manager - System tray icon with state management
 * Uses pre-rendered 32x32 PNG icons matching the welcome screen squircle style.
 * Icons generated by scripts/generate-tray-icons.js
 */

const { Tray, Menu, nativeImage } = require('electron');
const path = require('path');

// Tray states (ready tooltip is set dynamically in create())
const STATES = {
  ready:      { icon: 'tray-ready.png',      tooltip: 'MVP-Echo - Ready (Ctrl+Alt+Z)' },
  // Shown from launch until the engine finishes initializing. Reuses the
  // processing icon (same "busy, don't press yet" meaning) so no new asset is
  // needed; the tooltip carries the distinction. Before this state existed the
  // tray showed "Ready" while the hotkey was still dead.
  starting:   { icon: 'tray-processing.png', tooltip: 'MVP-Echo - Starting up...' },
  recording:  { icon: 'tray-recording.png',  tooltip: 'MVP-Echo - Recording...' },
  processing: { icon: 'tray-processing.png', tooltip: 'MVP-Echo - Processing...' },
  done:       { icon: 'tray-done.png',       tooltip: 'MVP-Echo - Copied!' },
  error:      { icon: 'tray-error.png',      tooltip: 'MVP-Echo - Error' },
  // A download is a WAIT, not a failure. Without a state of its own, pressing
  // the hotkey mid-download flashed the red error icon — indistinguishable from
  // a crash, for a machine that was working perfectly. Reuses the processing
  // icon exactly as `starting` does; setState appends the percentage.
  downloading: { icon: 'tray-processing.png', tooltip: 'MVP-Echo - Downloading GPU model...' },
};

class TrayManager {
  constructor() {
    this.tray = null;
    this.state = 'ready';
    /** Last tooltip actually written, so an identical one is not rewritten. */
    this.tooltip = null;
    this.doneTimeout = null;
    this.onTogglePopup = null;
    this.onQuit = null;
    this.iconCache = {};
  }

  /**
   * Load a pre-rendered tray icon PNG by state name.
   */
  getIcon(stateName) {
    if (this.iconCache[stateName]) {
      return this.iconCache[stateName];
    }

    const stateConfig = STATES[stateName];
    if (!stateConfig) return null;

    const iconPath = path.join(__dirname, 'icons', stateConfig.icon);
    const icon = nativeImage.createFromPath(iconPath);

    this.iconCache[stateName] = icon;
    return icon;
  }

  /**
   * Initialize the tray icon
   */
  create(callbacks = {}) {
    this.onTogglePopup = callbacks.onTogglePopup || (() => {});
    this.onQuit = callbacks.onQuit || (() => {});

    // Update ready tooltip with configured shortcut
    if (callbacks.shortcutLabel) {
      STATES.ready.tooltip = `MVP-Echo - Ready (${callbacks.shortcutLabel})`;
    }

    const icon = this.getIcon('ready');
    this.tray = new Tray(icon);
    this.tray.setToolTip(STATES.ready.tooltip);

    // Left-click toggles popup
    this.tray.on('click', () => {
      this.onTogglePopup();
    });

    // Right-click context menu
    this.updateContextMenu();

    return this.tray;
  }

  updateContextMenu() {
    const contextMenu = Menu.buildFromTemplate([
      {
        label: 'Show Transcription',
        click: () => this.onTogglePopup(),
      },
      { type: 'separator' },
      {
        label: 'Quit',
        click: () => this.onQuit(),
      },
    ]);
    this.tray.setContextMenu(contextMenu);
  }

  /**
   * Update tray state (icon + tooltip)
   */
  setState(state, detail) {
    if (!this.tray || !STATES[state]) return;

    // Clear any pending done->ready timeout
    if (this.doneTimeout) {
      clearTimeout(this.doneTimeout);
      this.doneTimeout = null;
    }

    const stateConfig = STATES[state];
    // Only touch the OS when something visibly changed. setImage() on every
    // call made the tray icon blink continuously during a download: the
    // renderer repaints on every state broadcast, and there are ~100 of those
    // per download. Rewriting an icon with the same icon is not free on
    // Windows — it is a visible redraw.
    if (state !== this.state) {
      this.tray.setImage(this.getIcon(state));
    }
    this.state = state;

    // `detail` is appended, never stored, so it cannot outlive the state that
    // carried it — a percentage still sitting on "Ready" would be a lie.
    const tooltip = detail ? `${stateConfig.tooltip} ${detail}` : stateConfig.tooltip;
    if (tooltip !== this.tooltip) {
      this.tray.setToolTip(tooltip);
      this.tooltip = tooltip;
    }

    // Auto-revert done -> ready after 3 seconds
    if (state === 'done') {
      this.doneTimeout = setTimeout(() => {
        this.setState('ready');
      }, 3000);
    }
  }

  /**
   * Get tray bounds for popup positioning
   */
  getBounds() {
    if (!this.tray) return null;
    return this.tray.getBounds();
  }

  destroy() {
    if (this.doneTimeout) {
      clearTimeout(this.doneTimeout);
    }
    if (this.tray) {
      this.tray.destroy();
      this.tray = null;
    }
  }
}

module.exports = TrayManager;
// Exported for test/tray-manager.test.js — the state table is the contract.
module.exports.STATES = STATES;
